runtime: python39
entrypoint: gunicorn -b :$PORT galleria.wsgi

# This sample incurs costs to run on the App Engine flexible environment.
# See https://cloud.google.com/appengine/pricing for details.

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "bridger.settings"
  # Add any other environment variables you need, for example:
  # SECRET_KEY: "your-secret-key"
  # DATABASE_URL: "your-database-url"
